files:
  DATA_DIR: "data/"
  FILE_NAME: "data.zip"
  DL_IMG_DIRS: 
    - "data/Train/Rural/images_png"
    - "data/Train/Urban/images_png"
  DL_MASK_DIRS:
    - "data/Train/Rural/masks_png"
    - "data/Train/Urban/masks_png"
  DEST_IMG_DIR:  "data/images/"
  DEST_MASK_DIR: "data/masks/"
  INTERIM_DIR: "data/interim/"
  SPLIT_DIR: "data/split/"
  TRAIN_IMG_DIR : "data/split/train/"
  VAL_IMG_DIR : "data/split/val/"
  TEST_IMG_DIR : "data/split/test/"
  MODEL_READ_PATH: "../drive/MyDrive/sis_models/UNetWithResnet50Encoder_unfreeze1.pth"
  MODEL_SAVE_PATH: "../drive/MyDrive/sis_models/UNetWithResnet50Encoder_unfreeze1.pth"

data_ingestion:
  FLAG: True
  DOWNLOAD_FLAG: True
  DOWNLOAD_FROM_GDRIVE: True
  # Gdrive id "1xbnKVN5aRMlpxISXgutzQO0hPT_b4lMi" or "https://zenodo.org/record/5706578/files/Train.zip?download=1"
  # Or https://landcover.ai.linuxpolska.com/download/landcover.ai.v1.zip for another dataset
  URL: "1EyfuxY9Dkb_l4bZfRcHeKZwD3NMX2xwc"

data_split:
  split_image:
    PATCH_SIZE: 256
    SELECTION_THRESHOLD: 0.9
    LABELS_TO_REMOVE: [0]
    NEW_LABEL_MAP:
      1: 0
      2: 1
      3: 2
      4: 3
      5: 4
      6: 5
      7: 6
  train_val_split:
    TRAIN_SIZE: 0.7
    VAL_SIZE: 0.15
    RANDOM_STATE: 42

dataloader: 
  BATCH_SIZE: 32
  NUM_WORKERS: 2
  PIN_MEMORY: False

model: 
  LEARNING_RATE: 0.0001
  IN_CHANNELS: 3
  OUT_CHANNELS: 7
  FEATURE_NUMS: [64, 128, 256, 512]
  NUM_EPOCHS: 13
  LAST_N_LAYERS_TO_UNFREEZE: 1 # Unfreeze last n layers of pretrained backbone
  LOAD_MODEL: False

  # types: background – 1, building – 2, road – 3,water – 4, barren – 5,forest – 6, agriculture – 7. And the no-data regions were assigned 0