files:
  DATA_DIR: "data/"
  FILE_NAME: "data.zip"
  DL_IMG_DIRS: 
    - "data/Train/Rural/images_png"
    - "data/Train/Urban/images_png"
  DL_MASK_DIRS:
    - "data/Train/Rural/masks_png"
    - "data/Train/Urban/masks_png"
  DEST_IMG_DIR:  "data/images/"
  DEST_MASK_DIR: "data/masks/"
  INTERIM_DIR: "data/interim/"
  SPLIT_DIR: "data/split/"
  TRAIN_IMG_DIR : "data/split/train/"
  VAL_IMG_DIR : "data/split/val/"
  TEST_IMG_DIR : "data/split/test/"
  MODEL_READ_PATH: "../drive/MyDrive/sis_models/UNetWithResnet50Encoder_unfreeze2_512.pth"
  MODEL_SAVE_PATH: "../drive/MyDrive/sis_models/UNetWithResnet50Encoder_unfreeze2_512.pth"

data_ingestion:
  FLAG: True
  DOWNLOAD_FLAG: True
  DOWNLOAD_FROM_GDRIVE: True
  # Gdrive id "1xbnKVN5aRMlpxISXgutzQO0hPT_b4lMi" or "https://zenodo.org/record/5706578/files/Train.zip?download=1"
  # Or https://landcover.ai.linuxpolska.com/download/landcover.ai.v1.zip for another dataset
  URL: "1EyfuxY9Dkb_l4bZfRcHeKZwD3NMX2xwc"

data_split:
  split_image:
    PATCH_SIZE: 512
    SELECTION_THRESHOLD: 0.95
    LABELS_TO_REMOVE: [0]
    NEW_LABEL_MAP:
      1: 0 # background
      2: 1 # building
      3: 2 # road
      4: 3 # water
      5: 4 # barren
      6: 5 # forest
      7: 6 # agriculture
  train_val_split:
    TRAIN_SIZE: 0.7
    VAL_SIZE: 0.15
    RANDOM_STATE: 42

dataloader: 
  BATCH_SIZE: 16
  NUM_WORKERS: 2
  PIN_MEMORY: False

model: 
  LEARNING_RATE: 0.0001
  IN_CHANNELS: 3
  OUT_CHANNELS: 7
  FEATURE_NUMS: [64, 128, 256, 512]
  NUM_EPOCHS: 13
  LAST_N_LAYERS_TO_UNFREEZE: 2 # Unfreeze last n layers of pretrained backbone
  LOAD_MODEL: True
  REDUCE_LR_FACTOR: 0.1
  REDUCE_LR_PATIENCE: 2

api:
  API_MODEL: "../models/UNetWithResnet50Encoder_unfreeze2_512.pth"
  colormap: 
    0: [128, 128, 128] # Background (label 0) - Black
    1: [128, 0, 0]     # Building (Label 1) - Dark Red
    2: [255, 165, 0] # Road (Label 2) - Gray
    3: [0, 0, 255]     # Water (Label 3) - Blue
    4: [77, 47, 20]   # Barren (Label 4) - Cream Yellow
    5: [0, 88, 0]     # Forest (Label 5) - Dark Green
    6: [185, 255, 71]  # Agriculture (Label 6) - Light Green