files:
  DATA_DIR: "data"
  FILE_NAME: "data.zip"
  DL_IMG_DIR: "data/images/"
  DL_MASK_DIR: "data/masks/"
  INTERIM_DIR: "data/interim/"
  SPLIT_DIR: "data/split/"
  TRAIN_IMG_DIR : "data/split/train/"
  VAL_IMG_DIR : "data/split/val/"
  TEST_IMG_DIR : "data/split/test/"
  MODEL_READ_PATH: "../drive/MyDrive/sis_models/UNetWithResnet50Encoder.pth"
  MODEL_SAVE_PATH: "../drive/MyDrive/sis_models/UNetWithResnet50Encoder.pth"

data_ingestion:
  FLAG: True
  URL: "https://landcover.ai.linuxpolska.com/download/landcover.ai.v1.zip"

data_split:
  split_image:
    PATCH_SIZE: 256
    SELECTION_THRESHOLD: 0.95
  train_val_split:
    TRAIN_SIZE: 0.7
    VAL_SIZE: 0.15
    RANDOM_STATE: 42

dataloader: 
  BATCH_SIZE: 32
  NUM_WORKERS: 2
  PIN_MEMORY: False

model: 
  LEARNING_RATE: 0.0001
  IN_CHANNELS: 3
  OUT_CHANNELS: 5
  FEATURE_NUMS: [64, 128, 256, 512]
  NUM_EPOCHS: 3
  LOAD_MODEL: True