name: Deploy API to AWS

on:
  workflow_run:
    workflows: ["Test Conda Environment"]
    branches: [ master ]
    types:
      - completed
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t sat_img_seg:latest -f docker/flask_app.dockerfile .
      - run: docker tag sat_img_seg ${{ secrets.DOCKER_USERNAME }}/sat_img_seg:latest
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/sat_img_seg:latest
      - name: Deploy to AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/sat_img_seg:latest
            sudo docker stop sat_img_seg
            sudo docker rm sat_img_seg
            sudo docker run -d --name sat_img_seg -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/sat_img_seg:latest


      