name: Deploy API to AWS

on:
  push:
    branches: [ development, master ]
  pull_request:
    branches: [ master ]
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t sat_img_seg -f .\docker\flask_app.dockerfile .
      - run: docker tag sat_img_seg ${{ secrets.DOCKER_USERNAME }}/sat_img_seg
      - run: docker push ${{ secrets.DOCKER_USERNAME }}/sat_img_seg
      - run: echo "Docker Image published to Docker Hub"


      